services:
  skydb:
    image: postgres:16
    environment:
      POSTGRES_DB: skyblock
      POSTGRES_USER: skyblock
      POSTGRES_PASSWORD: skyblock
    ports:
    - 5432:5432
    volumes:
    - type: volume
      source: db
      target: /var/lib/postgresql/data
    container_name: skydb
    networks:
      - skyblock

  # indexer:
  #   build: .
  #   container_name: skyblock-indexer
  #   networks:
  #     - skyblock
  #   depends_on:
  #     - skydb

volumes:
  db:

networks:
  skyblock:
    driver: bridge
