services:
  skydb:
    image: postgres:16
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: skyblock
      POSTGRES_PASSWORD: skyblock
    ports:
    - 5432:5432
    volumes:
    - type: volume
      source: db
      target: /var/lib/postgresql/data
    container_name: skydb
    networks:
      - skyblock



volumes:
  db:

networks:
  skyblock:
    driver: bridge


